/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsIdRouteImport } from './routes/applications/$id'
import { Route as AuthGmailCallbackRouteImport } from './routes/auth.gmail.callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGmailCallbackRoute = AuthGmailCallbackRouteImport.update({
  id: '/auth/gmail/callback',
  path: '/auth/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/auth/gmail/callback': typeof AuthGmailCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/auth/gmail/callback': typeof AuthGmailCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/auth/gmail/callback': typeof AuthGmailCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/review'
    | '/settings'
    | '/applications/$id'
    | '/auth/gmail/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/review'
    | '/settings'
    | '/applications/$id'
    | '/auth/gmail/callback'
  id:
    | '__root__'
    | '/'
    | '/review'
    | '/settings'
    | '/applications/$id'
    | '/auth/gmail/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  ApplicationsIdRoute: typeof ApplicationsIdRoute
  AuthGmailCallbackRoute: typeof AuthGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/gmail/callback': {
      id: '/auth/gmail/callback'
      path: '/auth/gmail/callback'
      fullPath: '/auth/gmail/callback'
      preLoaderRoute: typeof AuthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  ApplicationsIdRoute: ApplicationsIdRoute,
  AuthGmailCallbackRoute: AuthGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
